/**
 * Branded client-file PDF export — profile, targets, weight trend, compliance,
 * recent check-ins. Returns the jsPDF doc; caller saves/downloads.
 */
import { jsPDF } from 'jspdf'
import { format, subDays, parseISO } from 'date-fns'

const C = {
  bg:     [8,   9,   15 ],
  card:   [20,  27,  46 ],
  cream:  [216, 230, 244],
  accent: [72,  120, 176],
  muted:  [96,  120, 144],
}

export function generateClientReportPDF(client, coachName = '') {
  const doc = new jsPDF({ unit: 'pt', format: 'letter' })
  const W = doc.internal.pageSize.getWidth()
  let y = 0

  const header = () => {
    doc.setFillColor(...C.bg); doc.rect(0, 0, W, 92, 'F')
    doc.setTextColor(...C.cream); doc.setFont('helvetica', 'bold'); doc.setFontSize(20)
    doc.text('MACRO', 40, 40)
    const w = doc.getTextWidth('MACRO')
    doc.setTextColor(...C.accent); doc.text('STACK', 40 + w, 40)
    doc.setTextColor(...C.muted); doc.setFontSize(9); doc.setFont('helvetica', 'normal')
    doc.text(`CLIENT REPORT · ${format(new Date(), 'MMM d, yyyy')}${coachName ? ` · COACH: ${coachName.toUpperCase()}` : ''}`, 40, 58)
    doc.setTextColor(...C.cream); doc.setFont('helvetica', 'bold'); doc.setFontSize(15)
    doc.text((client.name || 'Client').toUpperCase(), 40, 80)
    y = 116
  }
  const sectionTitle = (t) => {
    if (y > 720) { doc.addPage(); header() }
    doc.setTextColor(...C.accent); doc.setFontSize(10); doc.setFont('helvetica', 'bold')
    doc.text(t, 40, y); y += 6
    doc.setDrawColor(...C.accent); doc.setLineWidth(0.5); doc.line(40, y, W - 40, y)
    y += 16
  }
  const row = (label, value) => {
    if (y > 740) { doc.addPage(); header() }
    doc.setFont('helvetica', 'normal'); doc.setFontSize(10)
    doc.setTextColor(...C.muted); doc.text(label, 40, y)
    doc.setTextColor(30, 30, 30); doc.text(String(value ?? '—'), 210, y)
    y += 16
  }

  header()

  // ── Profile ──
  sectionTitle('PROFILE')
  row('Email', client.email || '—')
  row('Height', client.height || '—')
  row('Phone', client.phone || '—')
  if (client.tags?.length) row('Tags', client.tags.join(', '))
  y += 6

  // ── Targets ──
  sectionTitle('DAILY TARGETS')
  row('Calories', `${client.goals.calories} kcal`)
  row('Protein', `${client.goals.protein} g`)
  row('Carbs', `${client.goals.carbs} g`)
  row('Fat', `${client.goals.fat} g`)
  y += 6

  // ── Weight ──
  sectionTitle('WEIGHT')
  const wl = [...(client.weightLog || [])].sort((a, b) => a.date.localeCompare(b.date))
  if (wl.length) {
    const first = wl[0], last = wl[wl.length - 1]
    row('Entries', wl.length)
    row('First', `${first.value} ${first.unit} on ${format(parseISO(first.date), 'MMM d, yyyy')}`)
    row('Latest', `${last.value} ${last.unit} on ${format(parseISO(last.date), 'MMM d, yyyy')}`)
    row('Change', `${(last.value - first.value) > 0 ? '+' : ''}${(last.value - first.value).toFixed(1)} ${last.unit}`)
  } else {
    row('Entries', 'No weight logged yet')
  }
  y += 6

  // ── Compliance (last 30 days) ──
  sectionTitle('LOGGING — LAST 30 DAYS')
  let logged = 0, cals = 0
  for (let i = 0; i < 30; i++) {
    const d = format(subDays(new Date(), i), 'yyyy-MM-dd')
    const entries = client.log?.[d] || []
    if (entries.length) { logged++; cals += entries.reduce((s, e) => s + (e.calories || 0), 0) }
  }
  row('Days logged', `${logged} / 30`)
  row('Avg intake (logged days)', logged ? `${Math.round(cals / logged)} kcal` : '—')
  y += 6

  // ── Recent check-ins ──
  sectionTitle('RECENT CHECK-INS')
  const checkins = (client.checkins || []).slice(0, 4)
  if (!checkins.length) row('Check-ins', 'None submitted yet')
  for (const k of checkins) {
    if (y > 700) { doc.addPage(); header() }
    doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.setTextColor(30, 30, 30)
    doc.text(`${k.createdAt ? format(parseISO(k.createdAt), 'MMM d, yyyy') : ''}${k.weight ? `  ·  ${k.weight} ${k.weightUnit}` : ''}`, 40, y)
    y += 14
    doc.setFont('helvetica', 'normal'); doc.setFontSize(9); doc.setTextColor(...C.muted)
    const answers = k.answers?.length
      ? k.answers.map((a) => `${a.label}: ${a.type === 'scale' ? (a.value ? a.value + '/5' : '—') : a.type === 'yesno' ? (a.value == null ? '—' : a.value ? 'Yes' : 'No') : (a.value || '—')}`)
      : [`Adherence: ${k.adherence ?? '—'}/5`, `Hunger: ${k.hunger ?? '—'}/5`, `Energy: ${k.energy ?? '—'}/5`, k.notes ? `Notes: ${k.notes}` : null].filter(Boolean)
    for (const line of answers) {
      const wrapped = doc.splitTextToSize(line, W - 100)
      if (y + wrapped.length * 11 > 760) { doc.addPage(); header() }
      doc.text(wrapped, 52, y)
      y += wrapped.length * 11 + 2
    }
    y += 8
  }

  // Footer
  doc.setTextColor(...C.muted); doc.setFontSize(8)
  doc.text('Generated by MacroStack · getmacrostack.com', 40, 770)

  return doc
}
