import {useEffect,useState,useCallback} from 'react';
import {resourceAssignments,resourceCommand} from './resourcesApi';
import ResourceContent from './ResourceContent';
import {resourceKinds} from './resourceModel';
import Resources from './Resources';
import {Button,Modal,Alert,Empty,useAction} from './ui';
export default function CustomerResources({relationship,staff,onRefresh,openPicker=false,onPickerOpened}) {
 const [rows,setRows]=useState([]),[loaded,setLoaded]=useState(false),[selected,setSelected]=useState(null),[answers,setAnswers]=useState({}),[adding,setAdding]=useState(false);
 const {busy,error,run,setError}=useAction();
 const reload=useCallback(async()=>{setRows(await resourceAssignments({relationship_id:relationship.id}));setLoaded(true)},[relationship.id]);
 useEffect(()=>{let active=true;resourceAssignments({relationship_id:relationship.id}).then(r=>{if(active){setRows(r);setLoaded(true)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[relationship.id,setError]);
 return <section className="retail-section retail-resources"><div className="resource-toolbar"><div><h2>{staff?'Shared resources':'Resources from your store'}</h2><p>{staff?'Assigned meal plans, forms and guides, with saved responses.':'Your store’s guides, forms and personalized meal plans.'}</p></div>{staff&&<Button primary disabled={relationship.status!=='active'} onClick={()=>setAdding(true)}>Add from Resources</Button>}</div><Alert error={error}/>{!loaded&&!error?<p role="status">Loading shared resources…</p>:!rows.length?<Empty>No resources shared yet.</Empty>:<div className="resource-list">{rows.map(a=><button className="resource-assignment" key={a.id} onClick={()=>{setSelected(a);setAnswers(a.answers||{})}}><div><strong>{a.title}</strong><span>{resourceKinds[a.kind]} · {new Date(a.assigned_at).toLocaleDateString()}{a.due_date?` · Due ${a.due_date}`:''}</span></div><span className="retail-badge">{a.completed_at?(a.kind==='form'?'Completed':'Read'):a.kind==='form'?'To complete':'Open →'}</span></button>)}</div>}
 {(adding||openPicker)&&<Modal wide title="Add from Resources" onClose={()=>{setAdding(false);onPickerOpened?.()}}><Resources location={{id:relationship.location_id}} customer={relationship} onDone={async()=>{await reload();await onRefresh?.();setAdding(false);onPickerOpened?.()}}/></Modal>}
 {selected&&<Modal wide title={selected.title} onClose={()=>setSelected(null)}><form className="resource-preview" onSubmit={e=>{e.preventDefault();run(async()=>{await resourceCommand('complete',{id:selected.id,answers});await reload();setSelected(null);await onRefresh?.()})}}><p className="retail-eyebrow">{resourceKinds[selected.kind]} · Saved version {selected.resource_version}</p>{selected.message&&<p className="resource-message">{selected.message}</p>}<Alert error={error}/>{selected.kind==='meal_plan'&&<Button type="button" disabled={busy} onClick={()=>run(async()=>{const {loadPlanBranding,generateRetailPlanPDF}=await import('./planPDF');const brand=await loadPlanBranding(relationship.location_id);generateRetailPlanPDF({planName:selected.title,days:selected.content.days},{name:relationship.name},brand).save('nutrition-plan.pdf');})}>Download PDF</Button>}<ResourceContent resource={selected} answers={answers} readOnly={staff||!!selected.completed_at} onAnswer={(id,v)=>setAnswers(a=>({...a,[id]:v}))}/>{selected.completed_at&&<p>Completed {new Date(selected.completed_at).toLocaleString()}</p>}{!staff&&!selected.completed_at&&<Button primary type="submit" disabled={busy}>{busy?'Saving…':selected.kind==='form'?'Submit responses':'Mark as read'}</Button>}</form></Modal>}
 </section>;
}
