import {useEffect,useState} from 'react';
import {relationships} from './api';
import {resourceCommand} from './resourcesApi';
import {Button,Field,Modal,Alert,useAction} from './ui';
import NutritionEditor from './NutritionEditor';
import ResourceContent from './ResourceContent';
export default function ResourceUse({resource,location,customer,onClose,onDone}) {
 const [selected,setSelected]=useState(customer||null),[query,setQuery]=useState(''),[results,setResults]=useState([]),[offset,setOffset]=useState(0),[total,setTotal]=useState(0),[loading,setLoading]=useState(false);
 const [message,setMessage]=useState(''),[due,setDue]=useState(''),[review,setReview]=useState(false);
 const [requestId]=useState(()=>crypto.randomUUID());
 const {busy,error,run,setError}=useAction();
 useEffect(()=>{if(selected)return;let active=true;const timer=setTimeout(()=>{setLoading(true);relationships(location.id,{search:query,filter:'active',offset}).then(r=>{if(active){setResults(r.rows);setTotal(r.count);}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});},200);return()=>{active=false;clearTimeout(timer)}},[query,offset,location.id,selected,setError]);
 if(review&&selected&&resource.kind==='meal_plan')return <NutritionEditor relationship={selected} resource={resource} resourceMessage={message} requestIdOverride={requestId} onClose={onClose} onPublished={onDone}/>;
 return <Modal wide title={selected?`Use ${resource.title}`:'Choose a customer'} onClose={onClose}><div className="resource-use"><Alert error={error}/>{!selected?<><p>Choose an active, connected customer.</p><Field label="Find customer" value={query} onChange={v=>{setQuery(v);setOffset(0)}}/>{loading&&<p role="status">Finding customers…</p>}{results.map(c=><button className="resource-customer" key={c.id} onClick={()=>setSelected(c)}><strong>{c.name}</strong><span>{c.email}</span><span>Choose →</span></button>)}{!loading&&!results.length&&<p>No active customers match. Invite customers from the Customers tab first.</p>}<div className="retail-actions"><Button disabled={!offset} onClick={()=>setOffset(v=>v-50)}>Previous</Button><span>{total} customers</span><Button disabled={offset+50>=total} onClick={()=>setOffset(v=>v+50)}>Next</Button></div></>:<><p>For <strong>{selected.name}</strong></p><p>{resource.kind==='meal_plan'?'Next, personalize meals and daily targets before publishing.':'Review this resource before sharing a saved copy with the customer.'}</p>{resource.kind!=='meal_plan'&&<ResourceContent resource={resource}/>}<Field label="Accompanying chat message (optional)" multiline maxLength={2000} value={message} onChange={setMessage}/>{resource.kind==='form'&&<Field label="Due date (optional)" type="date" value={due} onChange={setDue}/>}<div className="retail-actions"><Button primary disabled={busy} onClick={()=>resource.kind==='meal_plan'?setReview(true):run(async()=>{await resourceCommand('assign',{resource_id:resource.id,resource_version:resource.version,relationship_id:selected.id,request_id:requestId,message,due_date:due});await onDone?.();onClose();})}>{busy?'Sharing…':resource.kind==='meal_plan'?'Personalize meal plan →':resource.kind==='form'?'Assign form':'Share guide'}</Button>{!customer&&<Button disabled={busy} onClick={()=>setSelected(null)}>Change customer</Button>}</div></>}</div></Modal>;
}
