import {useState} from 'react';
import {resourceCommand} from './resourcesApi';
import {teamRoles} from './permissions';
import {Button,Field,Select,Check,Alert,useAction} from './ui';
export default function ResourceGovernance({resource,corporate,canEdit,locations=[],onSaved}) {
 const [policy,setPolicy]=useState(resource.usage_policy||'personalize'),[required,setRequired]=useState(!!resource.staff_required),[distribution,setDistribution]=useState(resource.distribution||[]),[roles,setRoles]=useState(resource.required_roles||[]),[note,setNote]=useState('');
 const {busy,error,run}=useAction();
 const act=action=>run(async()=>{await resourceCommand(action,{id:resource.id,version:resource.version,review_revision:resource.review_revision,usage_policy:policy,staff_required:required,distribution,required_roles:roles,note});await onSaved();});
 return <section className="resource-governance"><h3>Company standards</h3><Alert error={error}/><p>{resource.usage_policy==='approved'?'Use as approved · protected content':'Personalization allowed'}{resource.review_status&&resource.review_status!=='none'?` · ${resource.review_status.replaceAll('_',' ')}`:''}</p>{resource.review_note&&<p>{resource.review_note}</p>}{corporate?<><Select label="Usage policy" value={policy} onChange={setPolicy}><option value="personalize">Personalize a copy</option><option value="approved">Use as approved</option></Select><details><summary>Distribution · {distribution.length?`${distribution.length} selected stores`:'All stores'}</summary><p>Leave all unchecked to distribute throughout the company.</p><div className="team-permissions">{locations.map(l=><Check key={l.id} checked={distribution.includes(l.id)} onChange={v=>setDistribution(d=>v?[...d,l.id]:d.filter(x=>x!==l.id))}>{l.name}</Check>)}</div></details>{resource.audience==='staff'&&<><Check checked={required} onChange={setRequired}>Require employees to acknowledge this material</Check>{required&&<details><summary>Required roles · {roles.length||'All'}</summary><div className="team-permissions">{Object.entries(teamRoles).map(([key,r])=><Check key={key} checked={roles.includes(key)} onChange={v=>setRoles(d=>v?[...d,key]:d.filter(x=>x!==key))}>{r.label}</Check>)}</div></details>}</>}<div className="retail-actions"><Button disabled={busy} onClick={()=>act('governance')}>Save standards</Button>{resource.review_status==='submitted'&&<Button primary disabled={busy} onClick={()=>act('approve')}>Approve for company use</Button>}</div>{resource.review_status==='submitted'&&<><Field label="Changes requested" multiline maxLength={2000} value={note} onChange={setNote}/><Button disabled={busy||!note.trim()} onClick={()=>act('request_changes')}>Request changes</Button></>}</>:canEdit&&resource.location_id&&resource.status==='draft'&&resource.review_status!=='submitted'?<Button disabled={busy} onClick={()=>act('submit')}>Submit for company approval</Button>:null}</section>;
}
