import {useCallback,useEffect,useState} from 'react';
import {BookOpen,ClipboardList,Utensils,Plus,ArrowUpRight,Search} from 'lucide-react';
import {resources,resourceAssignments,resourceCommand} from './resourcesApi';
import {Button,Field,Select,Modal,Alert,Empty,useAction} from './ui';
import ResourceEditor from './ResourceEditor';
import ResourceUse from './ResourceUse';
import ResourceContent from './ResourceContent';
import {resourceKinds} from './resourceModel';
const icons={meal_plan:Utensils,form:ClipboardList,guide:BookOpen};
export default function Resources({location,organizationId,manager=false,corporate=false,customer,onDone}) {
 const [items,setItems]=useState([]),[loaded,setLoaded]=useState(false),[query,setQuery]=useState(''),[kind,setKind]=useState('all'),[status,setStatus]=useState('published'),[preview,setPreview]=useState(null),[history,setHistory]=useState([]),[historyLoaded,setHistoryLoaded]=useState(false),[editing,setEditing]=useState(null),[using,setUsing]=useState(null),[notice,setNotice]=useState(''),[archive,setArchive]=useState(false);
 const {busy,error,run,setError}=useAction();
 const reload=useCallback(async()=>{setItems(await resources(location.id,organizationId));setLoaded(true)},[location.id,organizationId]);
 useEffect(()=>{let active=true;resources(location.id,organizationId).then(rows=>{if(active){setItems(rows);setLoaded(true)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[location.id,organizationId,setError]);
 useEffect(()=>{if(!preview)return;let active=true;resourceAssignments({resource_id:preview.id}).then(rows=>{if(active){setHistory(rows);setHistoryLoaded(true)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[preview,setError]);
 const visible=items.filter(r=>(!customer||(r.audience==='customer'&&r.status==='published'))&&(kind==='all'||r.kind===kind)&&(status==='all'||r.status===status)&&`${r.title} ${r.description}`.toLowerCase().includes(query.toLowerCase()));
 const canEdit=r=>manager&&(r.location_id===location.id||(corporate&&!r.location_id));
 return <div className="retail-resources"><div className="resource-toolbar"><div><h2>{customer?'Add from Resources':'Your reusable resources'}</h2><p>Meal plans, forms and guides. Create once, personalize and share.</p></div>{manager&&!customer&&<Button primary onClick={()=>setEditing({})}><Plus size={16}/> Create resource</Button>}</div><Alert error={error}/>{notice&&<p role="status">{notice}</p>}
 <div className="resource-filters"><Field label="Search resources" value={query} onChange={setQuery} placeholder="Find a plan, form or guide"/><Select label="Status" value={status} onChange={setStatus}>{(customer?['published']:['published','draft','archived','all']).map(v=><option key={v} value={v}>{v==='all'?'All statuses':v[0].toUpperCase()+v.slice(1)}</option>)}</Select></div>
 <nav className="resource-types" aria-label="Resource types">{[['all','All'],['meal_plan','Meal plans'],['form','Forms'],['guide','Guides']].map(([k,label])=><Button key={k} aria-pressed={kind===k} onClick={()=>setKind(k)}>{label}</Button>)}</nav>
 {!loaded&&!error?<p role="status">Loading resources…</p>:!visible.length?<Empty><Search size={24}/><h3>{query?'No matching resources':'Build your reusable toolkit'}</h3><p>{query?'Try another name or filter.':'Save a meal plan, create an intake form, or write a guide your team can use with customers.'}</p>{manager&&!customer&&<Button primary onClick={()=>setEditing({})}>Create your first resource</Button>}</Empty>:<div className="resource-list">{visible.map(r=>{const Icon=icons[r.kind];return <article className="resource-row" key={r.id}><div className="resource-icon"><Icon size={22}/></div><button className="resource-title" onClick={()=>{setHistoryLoaded(false);setPreview(r)}}><strong>{r.title}</strong><span>{r.description||`${resourceKinds[r.kind]} · ${r.audience==='staff'?'Internal team reference':'Ready to personalize for customers'}`}</span><small>{r.location_id?'Store':'Corporate'} · {r.audience==='staff'?'Staff only':'Customer-facing'} · {r.status} · {r.usage_count||0} uses · Updated {new Date(r.updated_at).toLocaleDateString()}</small></button><div className="resource-row-actions"><Button primary={r.status==='published'} onClick={()=>r.status==='published'&&r.audience==='customer'?setUsing(r):(setHistoryLoaded(false),setPreview(r))}>{r.audience==='staff'?'Open':r.status==='published'?'Use':'Preview'}<ArrowUpRight size={15}/></Button><details className="resource-menu"><summary aria-label={`Actions for ${r.title}`}>•••</summary><div><Button onClick={()=>{setHistoryLoaded(false);setPreview(r)}}>Preview & history</Button>{canEdit(r)&&<Button onClick={()=>setEditing(r)}>Edit</Button>}{manager&&r.allow_copy&&r.status==='published'&&<Button onClick={()=>setEditing({...r,id:undefined,copy_from:r.id,title:`${r.title} (copy)`,status:'draft'})}>Duplicate</Button>}{canEdit(r)&&r.status!=='archived'&&<Button onClick={()=>{setPreview(r);setArchive(true)}}>Archive</Button>}</div></details></div></article>})}</div>}
 {editing&&<ResourceEditor key={editing.id||'new'} initial={editing.kind?editing:undefined} location={location} organizationId={organizationId} allowCorporate={corporate} corporate={!!editing.id&&!editing.location_id} onClose={()=>setEditing(null)} onSaved={async()=>{await reload();setStatus('all');setNotice('Resource saved.')}}/>}
 {using&&<ResourceUse resource={using} location={location} customer={customer} onClose={()=>setUsing(null)} onDone={async()=>{setNotice('Resource shared with the customer.');await reload();setPreview(null);await onDone?.()}}/>}
 {preview&&!editing&&!using&&<Modal wide title={archive?'Archive resource?':preview.title} onClose={()=>{setPreview(null);setArchive(false)}}>{archive?<><p>This removes it from available resources. Customer assignments and responses remain available.</p><Alert error={error}/><Button disabled={busy} primary onClick={()=>run(async()=>{await resourceCommand('archive',{id:preview.id,version:preview.version});await reload();setPreview(null);setArchive(false);setNotice('Resource archived.');})}>Archive resource</Button></>:<div className="resource-preview"><Alert error={error}/><p className="retail-eyebrow">{resourceKinds[preview.kind]} · {preview.audience==='staff'?'Staff only':'Customer-facing'} · Version {preview.version}</p><p>{preview.description}</p><ResourceContent resource={preview}/><div className="retail-actions">{preview.kind==='meal_plan'&&<Button disabled={busy} onClick={()=>run(async()=>{const {loadPlanBranding,generateRetailPlanPDF}=await import('./planPDF');const brand=await loadPlanBranding(location.id);generateRetailPlanPDF({planName:preview.title,days:preview.content.days},{name:'Reusable template'},brand).save('meal-plan-template.pdf');})}>Download PDF</Button>}{preview.status==='published'&&preview.audience==='customer'&&<Button primary onClick={()=>setUsing(preview)}>Use with customer</Button>}{canEdit(preview)&&<Button onClick={()=>setEditing(preview)}>Edit resource</Button>}</div><section className="resource-history"><h3>Assignment history</h3><p>{historyLoaded?`${history.length}${history.length===500?'+':''} assignments visible to you`:'Loading assignments…'}</p>{history.map(a=><div className="retail-row" key={a.id}><div><strong>{a.retail_relationships?.name||'Customer'}</strong><p>{new Date(a.assigned_at).toLocaleDateString()} · Version {a.resource_version}{a.due_date?` · Due ${a.due_date}`:''}</p></div><div><span className="retail-badge">{a.completed_at?(a.kind==='form'?'Completed':'Read'):'Shared'}</span>{a.kind==='form'&&a.completed_at&&<details className="resource-response"><summary>View responses</summary><ResourceContent resource={a} answers={a.answers}/></details>}</div></div>)}</section></div>}</Modal>}
 </div>;
}
