-- Transactional test: no providers, retained accounts or real store records.
begin;
do $qa$
declare owner_id uuid:=gen_random_uuid(); other_id uuid:=gen_random_uuid(); r jsonb; again jsonb; c public.retail_contracts; op uuid; l public.retail_locations; rejected boolean;
begin
 insert into auth.users(id,email,email_confirmed_at) values(owner_id,'retail-signup-'||owner_id||'@example.invalid',now()),(other_id,'retail-signup-'||other_id||'@example.invalid',now());
 insert into public.profiles(id,name,role) values(owner_id,'Synthetic owner','client'),(other_id,'Synthetic outsider','client') on conflict(id) do nothing;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 execute 'set local role authenticated';
 rejected:=false;
 begin perform public.retail_command('start_workspace','{}');exception when others then rejected:=sqlerrm like '%separate retailer account%';end;
 if not rejected then raise exception 'Personal account allowed to create retailer workspace';end if;
 execute 'reset role';
 update auth.users set raw_app_meta_data='{"account_type":"retailer"}' where id=owner_id;
 execute 'set local role authenticated';
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 rejected:=false;
 begin perform public.retail_command('start_workspace','{"name":"","location_name":"Test","timezone":"America/Boise","billing_name":"Owner"}');exception when others then rejected:=true;end;
 if not rejected then raise exception 'Invalid name allowed';end if;
 r:=public.retail_command('start_workspace','{"name":"Synthetic self-service","location_name":"Test store","timezone":"America/Boise","billing_name":"Owner"}');
 again:=public.retail_command('start_workspace','{}');
 if r<>again then raise exception 'Retry created duplicate workspace';end if;
 if (select count(*) from public.retail_staff where organization_id=(r->>'organization_id')::uuid and user_id=owner_id)<>2 then raise exception 'Owner missing manager/admin roles';end if;
 select * into l from public.retail_locations where id=(r->>'location_id')::uuid;
 if l.enabled or not l.billing_required or l.sponsorship_ends_at is not null then raise exception 'Unpaid workspace activated';end if;
 select * into c from public.retail_contracts where location_id=l.id;
 if c.monthly_cents<>59900 or c.currency<>'usd' then raise exception 'Wrong price';end if;
 perform public.retail_command('contract',jsonb_build_object('location_id',l.id,'revision',c.revision,'billing_name','Updated owner','billing_email','owner@example.invalid','monthly_cents',1));
 if (select monthly_cents from public.retail_contracts where id=c.id)<>59900 then raise exception 'Price overwritten';end if;
 rejected:=false;begin perform public.retail_command('location',jsonb_build_object('location_id',l.id,'organization_id',l.organization_id,'name',l.name,'timezone',l.timezone,'enabled',true));exception when others then rejected:=sqlerrm like '%subscription%';end;
 if not rejected then raise exception 'Owner bypassed activation';end if;
 rejected:=false;begin perform public.retail_command('prospect',jsonb_build_object('location_id',l.id,'name','Blocked','email','blocked@example.invalid'));exception when others then rejected:=sqlerrm like '%subscription%';end;
 if not rejected then raise exception 'Unpaid customer creation allowed';end if;
 perform set_config('request.jwt.claim.sub',other_id::text,true);
 if exists(select 1 from public.retail_self_service_accounts) then raise exception 'Owner mapping exposed';end if;
 rejected:=false;begin perform public.retail_command('contract',jsonb_build_object('location_id',l.id,'revision',2,'billing_name','Outsider','billing_email','outsider@example.invalid'));exception when others then rejected:=true;end;
 if not rejected then raise exception 'Unrelated billing edit allowed';end if;
 execute 'reset role';
 update public.retail_contracts set stripe_customer_id='cus_signup_qa' where id=c.id;
 perform public.retail_sync_contract(c.id,'sub_signup_qa','cus_signup_qa','active',now()+interval '1 month');
 if not (select enabled from public.retail_locations where id=l.id) then raise exception 'Paid activation failed';end if;
 perform public.retail_sync_contract(c.id,'sub_signup_qa','cus_signup_qa','canceled',now());
 if (select enabled from public.retail_locations where id=l.id) then raise exception 'Canceled store remained enabled';end if;
 execute 'set local role authenticated';perform set_config('request.jwt.claim.sub',owner_id::text,true);
 select id into op from public.retail_operators where organization_id=l.organization_id;
 again:=public.retail_command('location',jsonb_build_object('organization_id',l.organization_id,'operator_id',op,'name','Second store','timezone','America/Boise'));
 if not exists(select 1 from public.retail_locations where id=(again->>'location_id')::uuid and billing_required and not enabled) then raise exception 'New location not gated';end if;
 if not exists(select 1 from public.retail_contracts where location_id=(again->>'location_id')::uuid and monthly_cents=59900) then raise exception 'New location billing missing';end if;
 execute 'reset role';
 update public.profiles set admin_override='locked' where id=owner_id;
 execute 'set local role authenticated';
 rejected:=false;begin perform public.retail_command('start_workspace','{}');exception when others then rejected:=true;end;
 if not rejected then raise exception 'Locked account allowed';end if;
 execute 'reset role';
end $qa$;
rollback;
select 'PASS retailer self-service: owner roles, retry, billing, isolation, activation and cancellation' as result;
